### ISSUE TITLE
Change mode of Navbar

### ISSUE THREAD

**Issue by aakzsh** [GDSC-USICT/GDSC-USICT-Web#3]
Change navbar mode to dark mode. Currently, the website just consists of one component which is the Navbar. We need to make it dark mode since the whole website would be made in dark mode.

**Comment by Giriraj-Roy** [comment]
Hello Sir,

I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by ola-nishant** [comment]
Please assign it to me @aakzsh

**Comment by Ansh1693** [comment]
Pls assign it to me

**Comment by aakzsh** [comment]
@Giriraj-Roy im assigning this issue to you, make the changes and create a PR.
Meanwhile, there would be more issues posted on this repository @Ansh1693 @ola-nishant, you can contribute there, thanks!

**Comment by aakzsh** [comment]
#4
